### PR TITLE
Add the dockerfile for server base image

### PR DESCRIPTION
**Pull request by loganhz**

### CODE REVIEW

**Comment by loganhz** [comment]
@yasker Can you help to build and push as `rancher/server-base`, please ? Thanks a lot

**Comment by yasker** [comment]
@cjellick @deniseschannon 

We need a naming policy for the server base image.

For now, we will have two versions of `server-base`, v1.6 and v2.0. I would suggest:
1. `rancher/server-base:v1.6` and `rancher/server-base:v2.0` will point to the latest build of the image for either version. (We will only deal with v1.6 in this commit)
2. When the image build completed, we can have a script to tag the end result image e.g. for 1.6 as both `rancher/server-base:v1.6-<date>` and `rancher/server-base:v1.6`. Then someone can manually push the image with both tags to the docker hub.

As an alternative, we may tag the image as `rancher/server-base:v1.6-<commit>-<date>` instead of `rancher/server-base:v1.6-<date>`, but IMO this Dockerfile won't be changed often, so I think we can get away with date tag only.

**Comment by cjellick** [comment]
my initial reaction is that we should not deviate from our simple semantic versioning that we currently use across the board. we only every do v<num>.<num>.<num>[-RC<num>]
adding commits or dates to that i think overcomplicates things.
i agree with having two lines for 1.0 and 2.0
but i would say that, perhaps, for 1.6.x,
it should start at rancher/server-base:v1.0.0, not 1.6.x
like, it doesnt need to be tied to 1.6
i would have rancher/server-base:v2.0.0 and iterate it separately 
but i would not worry about 2.0.0 too much

**Comment by yasker** [comment]
@cjellick @loganhz 

OK, let's use `version` script and tag to mark the release.

The first version will be `v1.0.0` (git tagged so it will be picked by version script). The version script is available at e.g. https://github.com/rancher/agent/blob/master/scripts/version

**Comment by loganhz** [comment]
@yasker updated

**Comment by yasker** [comment]
`rancher/server-base:v1.0.0` was pushed.

**Pull request merged**
